# Generated by Django 5.0.6 on 2024-06-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
